name: Build Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
   runs-on: ubuntu-latest
   
   steps:
      - uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.2
        with:
          deploy-updatesite: 'releng/org.palladiosimulator.pcm.confidentiality.reverseengineering.updatesite/target/repository'
          java-version: 17
          server-ssh-key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          remote-host: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          remote-port: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          remote-user: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          remote-target: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
