# This workflow will verify a Java project with Maven
name: Maven Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '4 2 * * 0' # once a week, Sundays at 02:04 UTC.
  workflow_dispatch: # manual trigger

jobs:
  verify:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Maven Verify
      run: mvn -B -U clean verify
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        NIST_NVD_API_KEY: ${{secrets.NIST_NVD_API_KEY}}
